# Yaml config file for category classification

input_file: null # json
cache_file: null # json
output_file: null # json line

convert_to_json: True

task_name:
  - criteria_tag
  - if_tag
  - math_tag

model_name: META-LLAMA/LLAMA-3-70B-CHAT-HF
name: llama-3-70b-instruct
endpoints:
  - api_base: null
    api_key: null
parallel: 50
temperature: 0.0
max_token: 512

max_retry: 2
retry_sleep: 10
error_output: $ERROR$